git test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
           MYSQL_DATABASE: mydatabase
         ports:
           - 3306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=3
 
     steps:
     - name: Checkout code
@@ -57,15 +57,18 @@ jobs:
         docker-compose build
         docker-compose up -d
 
-    # - name: Run tests against deployed application
-    #   run: |
-    #     HEALTH_CHECK_URL="http://localhost:your_application_port/health"
-    #     if curl -s --head "$HEALTH_CHECK_URL" | grep "200 OK" > /dev/null; then
-    #       echo "Application health check passed."
-    #     else
-    #       echo "Application health check failed."
-    #       exit 1
-    #     fi
+    - name: Print Docker Compose logs
+      run: docker-compose logs
+
+    - name: Run tests against deployed application
+      run: |
+        HEALTH_CHECK_URL="http://localhost:your_application_port/health"
+        if curl -s --head "$HEALTH_CHECK_URL" | grep "200 OK" > /dev/null; then
+          echo "Application health check passed."
+        else
+          echo "Application health check failed."
+          exit 1
+        fi
 
     - name: Test Database Initialization
       run: |
